[tool.poetry]
name = "metaphor-models"
version = "0.21.0"
description = ""
authors = ["Metaphor <dev@metaphor.io>"]
packages = [
    { include = "metaphor" },
]

[tool.poetry.dependencies]
python = "~=3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
