[tool.poetry]
name = "appsquared"
version = "0.1.1"
description = "Antigenic Prediction for Protein Sequences Pipeline"
authors = ["nicole.paterson <qxa4@cdc.gov>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.22.4"
pandas = "1.5.3"
setuptools = "^61.0"
biopython = "1.78"
scikit-learn = "1.2.2"
matplotlib = "3.6.2"
seaborn = "0.12.2"
cython = "0.29.32"
ticc = "0.1.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.conda-lock]
channels = [
    'conda-forge', 'defaults']
[tool.conda-lock.dependencies]
requires = ["salilab dssp==3.0.0"]
vmd = "vmd-python"
scipy = "1.11.1"
build-backend = "setuptools.build_meta"
[project]
name = "APPSquared"
version = "0.0.1"
authors = [
  { name="Nicole Paterson, Nicholas Kovacs", email="qxa4@cdc.gov" },
]
description = "A Pipeline to Characterize Influenza Antigenic Proteins"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/nicolepaterson/APPSquared"
"Bug Tracker" = "https://github.com/nicolepaterson/APPSquared/issues"
