[tool.poetry]
name = "icinga-pusher"
version = "0.1.8"
description = ""
authors = ["kmille <github@androidloves.me>"]
readme = "README.md"
packages = [{include = "icinga_pusher"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"


[tool.poetry.group.dev.dependencies]
pdbpp = "^0.10.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
