[tool.poetry]
name = "streamlit-dash"
version = "0.6.1"
description = "ğŸ–¼ï¸ An image select component for Streamlit"
authors = ["Onuralp SEZER <thunderbirdtr@gmail.com>"]
license = "MIT"
readme = "README.md"
# This is required so the frontend code is properly included in the wheel. 
include = ["streamlit_dash/frontend/build/**/*"]


[tool.poetry.dependencies]
python = "^3.8, !=3.9.7"
streamlit = "^1.19.0"

[tool.poetry.dev-dependencies]
watchdog = "^2.1.9"
black = "^22.6.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
