[tool.poetry]
name = "trycortex"
version = "1.0.4"
description = "Python library for Cortex"
authors = ["Charles <charlespun6@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.5"

# Install the "cortex" commandline script.
[tool.poetry.scripts]
cortex = "cortex.cli.cli:cortex"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
