[package]
name = "_kolo"
version = "2.12.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_kolo"
crate-type = ["cdylib"]

[dependencies]
bstr = "1.2.0"
once_cell = "1.17.1"
pyo3 = "0.18.0"
serde_json = { version = "1.0.91", features = ["arbitrary_precision", "preserve_order"] }
ulid = "1.0.0"

[build-dependencies]
pyo3-build-config = { version = "0.18.0", features = ["resolve-config"] }

[profile.release]

lto = true
# debug = true
