[project]
name = "miauw-base-service"
description = "base service and base worker class for miauw"
authors = [{name = "cheetahbyte", email = "contact@cheetahbyte.dev"}]
version = "1.2.1"
requires-python = ">=3.11"
dependencies = [
    "aio-pika"
]

[project.optional-dependencies]
dev = [
    "pytest"
]
