[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "turingproject"
version = "0.0.2"
authors = [{name = "Vitalijus Kiubis", email = "vitalijus.kiubis@gmail.com"}]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
